### ISSUE TITLE
Write parity conservation example notebook

### ISSUE THREAD

**Issue by redeboer** [ComPWA/qrules#109]
- [ ] Explain mechanism (LaTeX and markdown only)
- [ ] Work out example in for 𝐽/𝜓 → 𝐾⁰𝛴⁺𝑝̅
- [ ] Illustrate with a code example

**Comment by redeboer** [comment]
@Leongrim just add the notebook under `docs/usage` (best to copy one of the other notebooks there to have the same format).

If you want to build the notebook with HTML, add its name here

https://github.com/ComPWA/qrules/blob/1f38b20307436d200e7b95eb0a15d63b66b3538c/docs/usage.ipynb#L251-L255

and run `tox -e doc` (or `tox -e docnb` to generate cell outputs). More info on building documentation [here](https://compwa-org.readthedocs.io/en/stable/develop.html#documentation).

**Comment by Leongrim** [comment]
I'm not sure if I did everything correctly.
