### ISSUE TITLE
Implement toy problem that shows how to use `python-constraints`

### ISSUE THREAD

**Issue by grayson-helmholz** [ComPWA/qrules#266]
# General proposal description:

A possible toy-problem is the generation of _Configuration State Functions_  (CSF's) from Slater-Determinants which are known from Quantum Chemistry. The former form a basis for _Many-Electron-Wavefunctions_ (MEW's) which also obey the same quantum number constraints as the MEW (primarily occupation number, spin-magnitude and spin-projection).

For this problem no actual molecular orbitals and thus no explicit Slater-Determinants are needed. It suffices to treat the latter just as a _Occupation-Number-Vector_ (ONV) of the different spin-orbitals (ordered by energy).

### Procedure:
* Take the _Hartree-Fock ground state_ (for example: |11110000>   <-> 4 electrons).
* Generate the "excited" Slater-Determinants ( |11101000>, |11100100>, ....).
* Select the constraints for the MEW (ON, S², S_z).
* Find with `python-constraints` all CSF's which satisfy the same constraints.

### Possible additions:
* If a simple ONV-like formulation of the point-group representations of the orbitals can be found,
then spatial symmetry constraints can be added, which would show how extensible & reducible the implementation can be (see main-issue).

**Comment by redeboer** [comment]
Sounds like a nice example, the challenge will be to formulate this problem as CSP and to see how translates to the [`python-constraints2`](https://python-constraint.github.io/python-constraint) package (incidentally, this also goes into the direction #261).

I'm fine with investigating this in the form of a Python script. Once a solution is worked out, it would be nice to document it in [compwa.github.io/reports](https://compwa.github.io/reports).

**Comment by redeboer** [comment]
Summary of yesterday's meeting: _putting this issue on hold for now_ in favour of #272.
The worry is that the translation between CSFs and MEWs and then to CSP requires too much effort considering it is more of an exercise to become familiar with CSP and the `python-constraints` API.
