### ISSUE TITLE
Remove need for spin projection in `spin_magnitude_conservation` rule

### ISSUE THREAD

**Issue by redeboer** [ComPWA/qrules#280]
The [`spin_magnitude_conservation()`](https://qrules.readthedocs.io/0.10.x/api/qrules.conservation_rules.html#qrules.conservation_rules.spin_magnitude_conservation) rule requires [`SpinEdgeInput`](https://qrules.readthedocs.io/0.10.x/api/qrules.conservation_rules.html#qrules.conservation_rules.SpinEdgeInput), which has a `spin_projection` attribute, even though the rule implementation does not need it. This is a problem for #158. That issue either needs to work with spin projections for now (which is what we eventually want to remove, see #219) or we need to remove the need for providing a spin projection altogether by solving this issue first.

https://github.com/ComPWA/qrules/blob/e60ff895b4cf84be18291b6e4fe0ab516e75a493/src/qrules/conservation_rules.py#L694-L728

**Comment by grayson-helmholz** [comment]
Has been implemented in the `remove_spin-projections_in_cons-rules`-branch. Issue should be closeable after merging.
