### ISSUE TITLE
Specify key type of `EdgeSettings.qn_domains` and `NodeSettings.qn_domains`

### ISSUE THREAD

**Issue by redeboer** [ComPWA/qrules#281]
The key of `qn_domains` in `NodeSettings` and `EdgeSettings` can be typed with an alias like [`EdgeQuantumNumber`](https://github.com/ComPWA/qrules/blob/e60ff895b4cf84be18291b6e4fe0ab516e75a493/src/qrules/quantum_numbers.py#L111-L131) instead of `Any`, see https://github.com/ComPWA/qrules/pull/278#discussion_r1710182559). So the type would be something like:

```python
EdgeQuantumNumberType = Union[
    type[EdgeQuantumNumbers.pid],
    type[EdgeQuantumNumbers.mass],
    type[EdgeQuantumNumbers.width],
    ...
    type[EdgeQuantumNumbers.g_parity],
]
NodeQuantumNumberType = Union[
    type[NodeQuantumNumbers.l_magnitude],
    ...
]
```

**Comment by redeboer** [comment]
As an aside: all of this indicates that the decision to type everything with complicated `NewType` classes etc was a bad one. Issues like #280 suggest typing everything with `TypedDict` instead (so based on the name of the key rather than the key type itself).

**Comment by grayson-helmholz** [comment]
Has been implemented in the remove_spin-projections_in_cons-rules-branch. Issue should be closeable after merging.

**Comment by redeboer** [comment]
We'll have to do a bit more probably ;) There are a lot of places where `Any` should be replaced with `EdgeQuantumNumberType`/`NodeQuantumNumberType`.

Btw, for lower Python <3.9, use [`from typing import Type`](https://docs.python.org/3/library/typing.html#typing.Type) instead of `type`.
