### ISSUE TITLE
Pylance not recognising external modules anymore

### ISSUE THREAD

**Issue by grayson-helmholz** [ComPWA/qrules#300]
After resyncing uv pylance is not recognising external modules like attrs and sphinx_api_relink.

**Comment by redeboer** [comment]
Is this on a branch that has the updates from https://github.com/ComPWA/qrules/pull/299? You need `uv` [>=0.4.27](https://github.com/astral-sh/uv/releases/tag/0.4.27), or any package manager that supports [dependency groups](https://peps.python.org/pep-0735).

**Comment by redeboer** [comment]
https://github.com/ComPWA/qrules/issues/300#issuecomment-2446299571 solved the problem
